# Generated by Django 5.0.1 on 2025-05-09 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articulos',
            fields=[
                ('id_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_collation='SQL_Latin1_General_CP1253_CI_AI', max_length=255)),
                ('descripcion', models.TextField(db_collation='SQL_Latin1_General_CP1253_CI_AI')),
                ('lugar', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1253_CI_AI', max_length=100, null=True)),
                ('fecha_acontecimiento', models.DateField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1253_CI_AI', max_length=20, null=True)),
            ],
            options={
                'db_table': 'articulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1253_CI_AI', max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1253_CI_AI', max_length=255)),
                ('codename', models.CharField(db_collation='SQL_Latin1_General_CP1253_CI_AI', max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(db_collation='SQL_Latin1_General_CP1253_CI_AI', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(db_collation='SQL_Latin1_General_CP1253_CI_AI', max_length=150, unique=True)),
                ('first_name', models.CharField(db_collation='SQL_Latin1_General_CP1253_CI_AI', max_length=150)),
                ('last_name', models.CharField(db_collation='SQL_Latin1_General_CP1253_CI_AI', max_length=150)),
                ('email', models.CharField(db_collation='SQL_Latin1_General_CP1253_CI_AI', max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='categorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='SQL_Latin1_General_CP1253_CI_AI', max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1253_CI_AI', null=True)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1253_CI_AI', null=True)),
                ('object_repr', models.CharField(db_collation='SQL_Latin1_General_CP1253_CI_AI', max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField(db_collation='SQL_Latin1_General_CP1253_CI_AI')),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_collation='SQL_Latin1_General_CP1253_CI_AI', max_length=100)),
                ('model', models.CharField(db_collation='SQL_Latin1_General_CP1253_CI_AI', max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(db_collation='SQL_Latin1_General_CP1253_CI_AI', max_length=255)),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1253_CI_AI', max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(db_collation='SQL_Latin1_General_CP1253_CI_AI', max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(db_collation='SQL_Latin1_General_CP1253_CI_AI')),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(db_collation='SQL_Latin1_General_CP1253_CI_AI', max_length=100)),
                ('nombre_usuario', models.CharField(db_collation='SQL_Latin1_General_CP1253_CI_AI', max_length=50, unique=True)),
                ('direccion', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1253_CI_AI', max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1253_CI_AI', max_length=20, null=True)),
                ('email', models.CharField(db_collation='SQL_Latin1_General_CP1253_CI_AI', max_length=100, unique=True)),
                ('avatar_url', models.ImageField(blank=True, null=True, upload_to='avatares/')),
                ('es_administrador', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='imagenes_articulos',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('url_imagen', models.CharField(db_collation='SQL_Latin1_General_CP1253_CI_AI', max_length=255)),
                ('es_principal', models.BooleanField(blank=True, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'imagenes_articulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1253_CI_AI', max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='reportes_articulos',
            fields=[
                ('articulo_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tasks.articulos')),
                ('descripcion', models.TextField(db_collation='SQL_Latin1_General_CP1253_CI_AI')),
                ('fecha_reporte', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reportes_articulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='favoritos',
            fields=[
                ('usuario_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tasks.usuarios')),
                ('fecha_agregado', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'favoritos',
                'managed': False,
            },
        ),
    ]
